diegomura/react-pdf

examples/dom-bindings/src/App.js, examples/simple/example.js, packages/react-pdf-dom/src/Document.js, packages/react-pdf/src/elements/Catalog.js, packages/react-pdf/src/elements/index.js, packages/react-pdf/src/index.js, packages/react-pdf/src/pdf/index.js, packages/react-pdf/src/renderer.js, src/index.js
This also include a stupid mistake within tree traversal :)
This was needed for including fonts and other meta data within the PDF file. Needs to be always the root of the tree.
=> Add a document component for meta data.

LICENSE
By this change GitHub may be able to recognize the repository license and show it in the header.
=> Fix license recognition

.travis.yml
This is because yoga-layout needs to compile itself first before we can use it, and the dependencies to do so are not default available on linux.
For now I only enabled osx, in the future we need to do the same for windows and linux.
=> Run Travis only on the osx image for now

README.md
Nitpicky change, but valid nonetheless!
=> Fix indentation in README example

package.json, packages/react-pdf/specs/__snapshots__/pageSpec.js.snap, packages/react-pdf/specs/pageSpec.js, yarn.lock
According to jest snapshot testing documentation
(https://facebook.github.io/jest/docs/snapshot-testing.html) tests
should be deterministic that means that every time they run should
return the same result, but that was not posible with the previous
approach because date was changing every time tests runs, by stubbing
the date, tests can be deterministic again.
=> Fixing tests by stubing system date

packages/react-pdf/src/index.js
Problem:
```
➜  react-pdf git:(upstream-master) ✗ yarn example -- text               
yarn example v0.24.6
$ babel-node ./examples/index.js text
{ Error: Cannot find module './Stylesheet'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/theophile/new/react-pdf/packages/react-pdf/lib/index.js:11:19)
at Module._compile (module.js:571:32)
at loader (/home/theophile/new/react-pdf/node_modules/babel-register/lib/node.js:144:5)
at Object.require.extensions.(anonymous function) [as .js] (/home/theophile/new/react-pdf/node_modules/babel-register/lib/node.js:154:7)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12) code: …
```
=> fix(core/index): lowercase stylesheet import

packages/react-pdf-node/src/index.js
Closes https://github.com/diegomura/react-pdf/issues/152
This adds support for streaming the PDF response. As a result it can be directly used by subsequent node calls, instead of having to write a file and reading it again.
I made the renderToStream a first class citizen, with the `renderToFile` effectively using that stream. To prevent future confusion, the `render` method directs to the `renderToFile` method. However since it may confuse people, that method might need deprecation/removal in the future.
=> Support streaming output for nodejs

packages/react-pdf/src/renderer.js
=> Protect against parentInstance not being a node when unmounting

packages/react-pdf/src/mixins/borders.js
This PR brings a small improvement for border support.
When there was no border radius, the different borders of a `<View />` would not join correctly and leave blank space in the corner (see [before.pdf](https://github.com/diegomura/react-pdf/files/1771332/before.pdf)). This now fixed (result [after.pdf](https://github.com/diegomura/react-pdf/files/1771333/after.pdf)).
There are still some problems with border radius support I guess (different widths on adjacent sides, clipping content...). I will try to work on those later if I need to use border radius.
=> Better border support

packages/react-pdf/src/utils/image.js
The previous check was weak and did not check the actual extension (format) of the file. Now the test is done using a buffer.
This solves the problem when the image extension specified in the title does not match the actual format.
=> Check image extension with buffer

.babelrc
This will fix #266 
Removing `"modules": false,` will default modules to `"commonjs"`
=> Import error fix - Fix for issue #266

package.json
If you import package as `es` module you'll receive `cjs` module version instead of `es`. Most likely it's just a typo in module path definition in `package.json`. This PR solves this issue:
=> Fixed module path in package.json

src/dom.js
in this PR, I ensure users from previous version of `@react-pdf/renderer` (from version alpha 14 and below) to be able to keep their code that has `width` and `height` props to their `<Document />` component.
I put `width` and `height` before `style`, because users from previous package version (by my assumption) would not have `style` props defined. So that if migrating users defined `style` after they upgraded, the defined `style` will have its effect, the spread operator will replace the `width` and `height` from props.
=> ensure backward compatibility with height and width props

src/dom.js, src/index.js, src/renderer.js
- Make mandatory to wrap `Document` inside viewer or blob provider (that was causing issues when passing component instead of `Document` straight to components)
- Replace `Link` if has render prop
=> Improve API

package.json, src/elements/Image.js, src/elements/Node.js, src/elements/Text.js, src/stylesheet/yogaValue.js, tests/stylesheet.test.js, yarn.lock
Amazon Linux 1 ships with an outdated version of GCC. In order to deploy react-pdf successfully on Amazon Linux 1, we depend on [yoga-layout-prebuilt](https://github.com/vadimdemedes/yoga-layout-prebuilt), which works really well, instead of yoga-layout, which does not compile.
(Aside: to make yoga-layout(-prebuilt) run at an acceptable speed, we minified production code using [terser](https://github.com/terser-js/terser) instead of UglifyJS; it produced an almost magical improvement in execution speed, probably due to not stripping the `"use asm";` magic string from the asm.js output.)
References: #57, #142, #169
Resolves: #363 #337 #225 (would also address #211, #251, etc.)
=> Depend on yoga-layout-prebuilt instead of yoga-layout

src/dom.js, tests/domApi.test.js
This would allow arbitrary props to be passed through to the iframe viewer that `PDFViewer` returns. This lets us attach an `onLoad` event handler to the iframe, but would also allow any other props to be passed.
=> Pass props through from PDFViewer to iframe viewer

index.d.ts
Importing and using `Document` from `@react-pdf/renderer` throws this Typescript error: 
`TS2605: JSX element type 'Document' is not a constructor function for JSX elements.`
Looking at `@react-pdf`'s declaration file, I noticed that it tries to import the default export exported by `react`. `react` has no default export.
A workaround for this problem would be to enable `allowSyntheticDefaultImports` in the project's `tsconfig.json` file, but it's a workaround. 
This PR would fix the Typescript error without needing to enable `allowSyntheticDefaultImports`.
=> fix react import typing

src/font/index.js
This loads local fonts asynchronously to improve server-side performance by no longer blocking the main thread while font files are loaded.
~This depends on:~
- ~react-pdf/fontkit#4 being merged~
- ~this PR being updated with the new version of `react-pdf/fontkit`~
=> Open local fonts asynchronously

src/elements/Text.js, tests/text.test.js
When Text nodes are cloned, the container is copied over, including x offsets for each line. For `fixed` Text elements, this means that the x value was being accumulated on top of the original rect offset which resulted in this shifting effect that gradually grows worse for each page the `fixed` element shows up on.
I don't have an exact repro jsx but it would look roughly like this:
```jsx
<Document>
<Page>
{/* Foo shows up fine on the first page, but is shifted to the right 
8 pixels on subsequent pages 
*/}
<Text style={{ padding: 8 }} fixed>Foo</Text>
<LotsOfOtherContent />
</Page>
</Document>
```
Before fix:
After fix:
Fixes #361
=> fix(Text): dont add additional x value for lines

index.d.ts
the official docs mention width and height of PDFViewer support both number and string
=> add type string to PDFViewerProps width and height

jest.config.js, package.json, rollup.config.js, src/elements/Image.js, src/elements/Node.js, src/elements/Page.js, src/elements/Text.js, src/stylesheet/yogaValue.js, yarn.lock
This seems a cleaner way of using yoga-layout-prebuilt — it’s _really_ yoga-layout so it would be nicer to import yoga-layout but have the build system take care of turning that into yoga-layout-prebuilt for us. Should have thought of this for #364 really.
=> Alias yoga-layout-prebuilt to yoga-layout

src/utils/url.js, tests/url.test.js
This fixes using `mailto` src's on links. The mailto protocol does not contain `://`, so the previous Regex was causing mailto link srcs like `mailto:test@example.com` to show up as `http://mailto:test@example.com`
=> Fix email links

index.d.ts, src/elements/Document.js, src/font/emoji.js, src/font/font.js, src/font/hyphenation.js, src/font/index.js, src/stylesheet/transformFontWeight.js, src/stylesheet/transformStyles.js, src/utils/attributedString.js, tests/document.test.js, tests/font.test.js, tests/styleShorthands.test.js, tests/stylesInherit.test.js
This adds the ability to setup font-styles and font-weights when registering fonts:
```js
Font.register(`http://localhost:3000/Roboto-Regular.ttf`, {
family: 'Roboto'
})
Font.register(`http://localhost:3000/Roboto-Bold.ttf`, {
family: 'Roboto',
fontWeight: 'bold'
})
Font.register(`http://localhost:3000/Roboto-Italic.ttf`, {
family: 'Roboto',
fontWeight: 'normal',
fontStyle: 'italic'
})
Font.register(`http://localhost:3000/Roboto-BoldItalic.ttf`, {
family: 'Roboto',
fontWeight: 'bold',
fontStyle: 'italic'
})
```
When rendering, react-pdf will choose the appropriate font in the [same way the web does](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Fallback_weights).
Since we now support referring to different font files by using the same fontFamily value, IMO would be cool to …
=> Add font-weight and font-style support

tests/layout.test.js
Fix the test 'Absolute elements should be placed with percent left'
The page size was wrongly passed to `Document` instead of` Page`,
The test passed before only because the page size is A4 (595.28 vs 841.89) and
10% of 595.28 is 59.528 and internally the Yoga rounds to 60, the same as 10% of 600 (see #548 )
=> Fix page size on test

src/elements/Base.js
Since `zIndex` is not supported, rendering absolute elements first restricts the kind of things that can be done with the lib. For this reason we are going to stick to the JSX order for the elements
=> Render elements in JSX order

src/utils/pageSizes.js
Fixed a typo of `arraoy` => `array`.
=> Fix typo in getPageSize comment

src/stylesheet/borders.js, src/stylesheet/boxModel.js, src/stylesheet/index.js, src/stylesheet/objectPosition.js, src/stylesheet/transformOrigin.js, src/stylesheet/transformStyles.js, src/stylesheet/transformUnits.js, tests/unitsConversion.test.js
This PR adds support for `vh` and `vw` units. These units are useful to define length values relative to the size of the document's page.
=> Page percentage units (vh/vw)

examples/images/index.js, examples/pageWrap/index.js, examples/resume/index.js, examples/text/index.js
I've updated the params in Font.Register as recommended by the error message, which was pretty annoying since I wanted to quickly test the App examples and could not get any output.
The examples 'just work' now.
=> Updated Font.Register src param in examples

index.d.ts
According to the doc, the hyphenation callback is given the word as a
`string` and must return an `array` of `string` (`string[]` in TS).
That's how the features works according to my tests as well.
This commit fixes the type definition so as to accept the right type for
`word` (`string`).
=> Fix the HyphenationCallback Typescript definition

index.d.ts
According to the documentation, `fontStyle` and `fontWeight` have default values, so they must be optional in `FontDescriptor` and `register -> fonts`.
The `register` function also accepts two distinct possibilities : either passing `src` or `fonts`.
This commit fixes the type definitions so that the doc examples can be correct in a Typescript project.
These types (particularly `register`) can probably be made stricter by removing the `[key: string]: any;` clause.
=> Fix font Typescript definitions

index.d.ts
Complete, I hope, typings for Style interface. I went through the code to find the actually used and supported values. Some where not that easy so spot, as they span across yoga-layouts and pdfkit. Thus the `// ?`.
=> [typescript] Style typings

index.d.ts
It seems like last commit with Typescript types had missing borderRadius property. This commits add it.
=> Added missing style type

index.d.ts
This PR adds missing values for `textAlign` and `textDecoration` and also adds `borderWidth`, `borderColor` and `borderStyle`.
=> Add missing styles type for typescript

index.d.ts
We've used `borderRight: 1` and it seemed to work correctly. So is this maybe an oversight from https://github.com/diegomura/react-pdf/commit/d978f2460014f8915ff740100b49a121fc37178e?
=> Fixing borderRight type for typescript

index.d.ts
Props 
* `minPresenceAhead`
* `orhpans`
* `widows`
should be declared in index.d.ts file, accordingly with the documentation https://react-pdf.org/advanced#orphan-&-widow-protection.
=> Adds missing Orphan & widow protection props to index.d.ts

src/render/applyTransformations.js
There is an issue with the current implementation of parsing a `translate`  y coordinate.
https://rubular.com/r/VIZRKzIziTxc0e
https://rubular.com/r/VIZRKzIziTxc0e
The second match should be `20` and not `0`
https://rubular.com/r/P5KdsVsnjfCGJ6
https://rubular.com/r/c1LHkIUrLyL9rl
=> Parse translate y coordinate properly

src/index.js
@diegomura  It looks like we forgot to call `onRender` callback.
I've left out following line, not sure how important it was:
```
const layoutData = container.document.getLayoutData();
```
Here is a `master` version for comparison: https://github.com/diegomura/react-pdf/blob/master/src/index.js#L25
=> Call onRender again in v2

src/canvas.js, src/dom.js
This PR helps to clean the queue on blob and canvas unmounts.
Without it I was getting console warnings:
`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`
=> Empty the render queue immediately on unmount

index.d.ts
First of all, thanks for this great project. I really love it.
I want to use the fancy go-to functionally introduced here (#744)  with TypeScript. Unfortunately I'm not able to do this because the id prop is missing here:
https://github.com/diegomura/react-pdf/blob/ea026ae1167ceaec0c9dc906e7df42617c06e12f/index.d.ts#L152
This small PR is a small merge for you but will have much impact on my project. :-) My branch is based on your V2 branch so it can be merged easily.
=> TypeScript: Add id prop

examples/resume/Header.js, src/stylesheet/inherit.js, tests/stylesInherit.test.js
I found out that `text-transform` isn't inheritable propery in React PDF. But it should be (See [W3C info](https://www.w3.org/TR/CSS21/propidx.html)).
I updated `resume` example to debug this error (moved `textTranform` from each child to whole `detailColumn`):
=> Children should inherit text transform

index.d.ts
Actually, TypeScritp does not allow to set "table" as a display value. However, testing it with `//@ts-ignore` results in a fully working feature.
=> Allow setting "table" as display type

src/elements/Page.js
I tried looking around, and there was nowhere very obvious to add a test for this case. It can happen if you render `<Text>{null}</Text>`.
=> Ignores children elements that are null

index.d.ts
Hi @diegomura,
I need ID on img tag to create a link to it.
You haven't this property in BaseImageProps TS interface so I have added it.
Please could you accept my PR or write any suggestions :)
Lucas
=> TypeScript: Add ID property to BaseImageProps interface

packages/renderer/src/dom.js
A few fixes for `BlobProvider` in v2:
- Set loading: true when the document is re-rendering
- Ensure the ObjectURL is revoked when unmounting
- Clear the error when doc successfully loads
=> v2: Fixes for BlobProvider

babel.config.js
It looks like the only target in V2 packages is node. This works ok for all modern browsers but fails on older Edge and IE browsers.
=> Add IE target in babel config

packages/render/src/operations/setLink.js
Since `src.slice(1)` was removing the first character of `src` even if it was not a `goTo`, links were becoming incorrect.
This PR fixes this behavior.
=> [V2] fix Link to external URL

src/utils/pageSizes.js
Add the [ISO/IEC 7810](https://en.wikipedia.org/wiki/ISO/IEC_7810) credit card page size suggested in https://github.com/diegomura/react-pdf/issues/986
```javascript
// standard credit card
<Page size="ID1" orientation="landscape">
```
In the standard, there are ID-2 and ID-3 sizes but they are just references to A7, B7 formats, so I didn't add them
=> Add ISO/IEC 7810 ID-1 page size

packages/font/src/font.js
This bug meant that it was not possible to add fonts with different fontWeight, all fonts were registered with fontWeight 400.
=> fix(v2): Fix adding custom fonts of different weights

index.d.ts, src/elements/Image.js
This pull request does two things:
1. Show relevant warning message instead of `Cannot read property 'data' of null` when rendering `<Image src={undefined} />`
2. Make TypeScript types consistent with `src` prop specification
According to [`react-pdf.org`](https://react-pdf.org/components#image), default value of `src` prop is `undefined`. Indeed `undefined` is necessary when `src` receives value from Promise. I also found that [`resolveImage()`](https://github.com/diegomura/react-pdf/blob/ee0b35b7e2c57e96d675a3d08cb1042d6c528802/src/utils/image.js#L175) accepts `Buffer` as `src` argument which is not described in `react-pdf.org`. So I added relevant types.
=> Fix error handling for undefined src prop of <Image>

index.d.ts, src/elements/Document.js
Hey there,
First of all: I've been using react-pdf for a long time and love it!
One thing I recently needed (both for displaying, but even more for conditional rendering) was a `pageNumber` / `totalPages` for each **Page** component rather than having only the global one.
My Document consists of ~200 <Page> components each rendering song lyrics and chords for a songbook where I need to render the credits on the last page of each subPage.
This PR adds those 2 metrics with little changes allowing them to be used in View (`subPageNumber` only)  and Text (supporting both), just like the global ones.
It'd also resolve https://github.com/diegomura/react-pdf/issues/773 and probably help to achieve https://github.com/diegomura/react-pdf/issues/315.
Haven't looked into v2 right now, so I'm not too …
=> Adds subPageNumber and subPageTotalPages

index.d.ts
It seems like the typings were out of date. In the code bases, I was only able to find references to:
overflow: 'hidden'
and textOverflow: 'ellipsis'
Not sure, if there are other options allowed as well.
**Sorry, about that I closed the PR, thinking I could just reopen it again.**
=> update typescript typings

index.d.ts, src/elements/Text.js, tests/text.test.js
Typescript defs already defined a way to define the prop, but it did not have any affect. 
With this change, it would be easily possible to use different hyphenations for different parts of the PDF.
=> Allow hyphenationCallback on Text component to be configured by prop

src/elements/Text.js
Fixes issue #685, #1120 and #1085. The issues can be reproduced by the below code fragment:
```
const styles = StyleSheet.create({
body: {
padding: 40,
},
footer: {
position: 'absolute',
fontSize: 12,
bottom: 25,
left: 0,
right: 0,
textAlign: 'center',
color: 'grey',
},
});
const txt = Array.from(
{ length: 120 },
() => `
`,
)
.map((_, index) => `Line ${index + 1}${_}`)
.join('');
const doc = (
<Document>
<Page size="A4" style={styles.body}>
<Text>{txt}</Text>
<Text
style={styles.footer}
render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
fixed
/>
</Page>
</Document>
);
ReactPDF.render(doc, `${__dirname}/output.pdf`);
```
Screenshot after the fix:
=> Fixes issue #685, #1120 and #1085 - Text component hangs when its content is longer than 2 pages

index.d.ts
Hi @diegomura - sorry that I didn't add it in the previous Pull Request, but I've realized that I need ID props also on View and Page components to Link to them internally.
=> TypeScript: Add ID property to ViewProps & TextProps interfaces

packages/renderer/index.d.ts
There are duplicate keys `id` in `ViewProps` & `TextProps`. This PR resolves it.
=> Duplicate Id's removed from typings

packages/renderer/index.d.ts
Fixed error in type declaration of `pdf` function.
Returning type of methods `on` and `removeListener` was declared not as function returning value.
This PR fixes it.
=> Bad returning type for methods: on, removeListener

packages/renderer/src/index.js
Fixes #1067
For some reason if we disable `compress` on the pdfkit instance, the document renders correctly. Pushing this at least as an intermediate fix, but couldn't get to the bottom of why this was happening. Not sure I know enough about PDF internals to figure it out
=> Fix renderToString blank document

packages/renderer/index.d.ts
After migration to version 2, the access to the `Style` type is missing.
If we want to reference it we have to now use a hack, such as `typeof myStyles.myStyle` which is not ideal.
This PR exposes `Style` as `ReactPDF.Style`.
=> docs: bring back access to Style type

packages/layout/src/image/fetchImage.js, packages/layout/src/image/getSource.js, packages/layout/src/image/resolveSource.js, packages/layout/tests/image/getSource.test.js, packages/layout/tests/image/resolveSource.test.js, packages/types/image.d.ts
The PR brings support of not url only factories, async sources, async factories for `Image` component.
```jsx
<View>
{/* Sources */}
<Image src={url} />
<Image src={{ uri: valid-url, method: 'GET' }} />
<Image src={buffer} />
<Image src={{ data: buffer, format: 'png' }} />
{/* Source factories */}
<Image src={() => url} />
<Image src={() => ({ uri: valid-url, method: 'GET' })} />
<Image src={() => buffer} />
<Image src={() => ({ data: buffer, format: 'png' })} />
{/* Async sources */}
<Image src={Promise.resolve(url)} />
<Image src={Promise.resolve({ uri: valid-url, method: 'GET' })} />
<Image src={Promise.resolve(buffer)} />
<Image src={Promise.resolve({ data: buffer, format: 'png' })} />
{/* Async source factories */}
<Image src={async () => url} />
<Image src={async () => ({ uri: …
```
=> feat: add support of source factories for Image component

packages/renderer/src/dom.js
This change will allow Snowpack (or any rollup-related build system) work without the need to workaround mixed esm/commonjs dependencies as described https://github.com/snowpackjs/snowpack/discussions/1321
=> Change renderer queue require to import statement

packages/layout/src/text/fontSubstitution.js, packages/layout/src/text/ignoreChars.js
Related to #777 
This doesn't fix the root cause of why fragments intermittently have no font property, but it does prevent the app from crashing if there is no font.
=> Don’t call hasGlyphForCodePoint if font is null

packages/types/style.d.ts
Fixes https://github.com/diegomura/react-pdf/issues/1320. Adding only flexbox types here. `display: block` don't think has any effect on this lib. If I'm mistaken I'll add it in a separate PR. Thanks!
=> fix: flexbox types

packages/layout/src/image/fetchImage.js, packages/layout/tests/image/resolveSource.test.js, packages/types/image.d.ts
When resolving Image's source prop, if `src`/`source` is `undefined`, `fetchImage` will show relevant error message and return:
https://github.com/diegomura/react-pdf/blob/66d6259971e99846602d69de85fcbba98825d608/packages/layout/src/image/fetchImage.js#L18-L20
However, if `src`/`source` is not `undefined` but function returning `undefined`, `fetchImage` will pass through the above `if` block, invoke `resolveImage` and encounter `Cannot read property 'data' of undefined` error when evaluating `src.data`:
https://github.com/diegomura/react-pdf/blob/66d6259971e99846602d69de85fcbba98825d608/packages/image/src/resolve.js#L159-L160
This pull request adds code that will show relevant error message and return before invoking `resolveImage`, when `src`/`source` is function returning `undefined`.
=> feat: error handling when source factories of Image return undefined

packages/renderer/index.d.ts
The `StyleSheet` type for `@react-pdf/renderer` has a number of properties that don't actually exist. We noticed this issue when upgrading from v1 to v2 because `StyleSheet.flatten` was undefined at runtime. This seems intentional, since the actual `StyleSheet` export is just this:
https://github.com/diegomura/react-pdf/blob/7ddaa1858433dd401a7382aed2fe316c408b1bf4/packages/renderer/src/index.js#L126-L128
So this pull request makes the `StyleSheet` type accurate to what's actually exported.
This seems like a backwards compatibility issue though, since at least `StyleSheet.flatten`, `StyleSheet.resolve`, etc. did previously exist in v1.
=> Remove incorrect types from StyleSheet.

packages/types/style.d.ts
`Yoga-loyout` doesn't support flexbox ordering
fix #1340
=> Remove flexbox ordering from types

packages/examples/README.md, packages/renderer/README.md
Fixing examples links not working and images not showing in README files:
- Fixed broken paths (also, removed Images example as it doesn't appear to be around anymore).
- Added anchor element pointing to example folder for each image, instead of letting GitHub adding one automatically that points to the thumbnail file.
- Also, removed rogue spaces indentation in favour of tabs (which seems to be the preferred style) for a consistant indentation.
=> Fix examples in README

packages/renderer/src/dom.js
Related to #1326
Main issue - event added with `pdfInstance.on('change', queueDocumentRender)` were never removed. 
Since the implementation is a singleton all the past events were re-triggered
Update cleanup logic so that the previous `state.url` is always revoked
during a `useEffect` cleanup
This would also revoke the blob url when the hook is done and unmounts
I went with the `useEffect` cleanup function as it will run for each previous `state.url` 
as well as when a component using the hook unmounts in the end
---
I think the easiest way to test this is manually
1. Have a sample PDF document 
2. Have something that uses the `usePDF` hook (I think everything uses it internally ATM)
3. Trigger updates
4. Monitor the "Network" tab for `blob:...` urls 
5. You should be able to open the …
=> Fix Object URL cleanup in `usePDF`

packages/renderer/src/index.js
When you render multiple PDFs, since all events are kept in the same object
it will emit events to all usages and not only to the one that changed
Let's say I have 3 pdf previews, I'll use the hook for simplicity
```jsx
const [a, updateA] = usePDF({ document: Document_A });
const [b, updateB] = usePDF({ document: Document_B });
const [c, updateC] = usePDF({ document: Document_C });
useEffect(() => {
updateB();
}, [somethingThatUpdatesOnlyB])
```
Each hook registers a listener 
https://github.com/diegomura/react-pdf/blob/a21154486d41597aadd8b44b0d3b6c882a1cfd15/packages/renderer/src/dom.js#L45-L46
When `updateB()` is called this this will trigger a change and all listeners would be invoked
https://github.com/diegomura/react-pdf/blob/a21154486d41597aadd8b44b0d3b6c882a1cfd15/packages/renderer …
=> refactor(renderer): move events to the closure of `pdf`

packages/layout/src/svg/layoutText.js, packages/layout/src/text/getAttributedString.js, packages/types/style.d.ts, yarn.lock
Adds functionality for specifying multiple values for the `textDecoration` style attribute (Related to #809). 
This brings the `textDecoration` attribute in this library closer in line to  the standard CSS `text-decoration` attribute so it seems like a logical addition (and something that I was looking for in this library).
In particular, this change allows for specifying either `'underline line-through'` or `'line-through underline'` while disallowing invalid combinations such as `'underline none'`.  
I've updated the Typescript types as well to include `'underline line-through'` or `'line-through underline'` as valid values for the `textDecoration` style attribute.
I am unsure on how to approach implementing a test for this functionality or if one is needed, so any input on that front …
=> Add support for multiple text decorations

packages/types/style.d.ts
Allow strings for borderWidth in Typescript
=> Update borderWidth type to accept string

packages/types/style.d.ts
Hi, just a small fix to add zIndex property support to defined types.
Thanks for your work !
=> Fix missing style type for zIndex support

packages/renderer/package.json, packages/types/font.d.ts
typings field seems obsoled / deprecated
i can't find any information about it, so i change it to [`types`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)
export `HyphenationCallback` because it being used in `node.d.ts`
=> fix: use `types` field, fix exports

packages/layout/src/steps/resolveInheritance.js, packages/layout/tests/steps/resolveInhritance.test.js
fix merge `textDecoration` style in inherited nodes
fix #1489
=> fix textDecoration inheritance

src/utils/attributedString.js
Hi @diegomura 
Can you please release this patch for links in `react-pdf` v1?
now links doesn't works when they have other text elements inside, like this
```html
<Text>text: <Link src="https://link.com/"><Text style={bold}>link</Text></Link></Text>
<Text>text: <Link src="https://link.com/"><Text style={cursive}>link</Text></Link></Text>
```
this happen because `getFragments` function lose `src` prop when process `Link` children, so I fix that
=> apply patch for links from v2 to v1 too

packages/fontkit/src/glyph/CFFGlyph.js
I also have an open PR to fontkit. https://github.com/foliojs/fontkit/pull/267
=> fix: scoping issue on `phase` variable

package.json
Hello! @jeetiss :)
We're here again~~
We read your issue #1625 , and we think that we solved this issue!
In the package.json file, "husky" part might cause problem.
In "pre-commit" part, we think "git add ." is useless and it cause bug.
So we deleted "git add ." and when we add/commit 1 file of 2 file(or more),  it was confirmed that only the added file was uploaded.
If our fix is wrong, please comment us!
Thank you for reading this PR, and have a wonderful day~!
Desktop
- OS : Windows 10
- Browser : Chrome
- React-pdf version : 2.0.0
=> fix : bug fix about husky & lint-staged

.changeset/metal-stingrays-roll.md, packages/renderer/package.json, yarn.lock
`@react-pdf/renderer` uses `scheduler@0.15.0`
`react-reconciler@0.23.0` uses `scheduler@0.17.0`
as result we have two `scheduler` instances in bundle
pr fix this
=> fix: deduplicate scheduler

.changeset/violet-pears-bake.md, packages/pdfkit/rollup.config.js, packages/pdfkit/src/mixins/attachments.js
`crypto-js` contains a lot of hash algorithms and functions, but `pdfkit` uses only `md5`
I change the imports to include only `md5` code to bundle, it should save `~42kb`
=> fix: import only `md5` hash from `crypto-js`

.changeset/beige-wombats-jump.md, package.json, packages/fontkit/package.json, packages/fontkit/rollup.config.js, yarn.lock
I updated `dfa` to latest version, added it to browser bundle and process with babel to avoid problems with modern code as in #1061
deduplicate `regenerator-runtime` with update to `@babel/runtime/regenerator`
and skip `core-js@2` that should fix #1608
=> fix: bundle latest `dfa` to fontkit

.changeset/seven-moles-pull.md, babel.config.js, packages/font/package.json, packages/fontkit/package.json, packages/image/package.json, packages/layout/package.json, packages/pdfkit/package.json, packages/render/package.json, packages/renderer/package.json, packages/stylesheet/package.json, packages/svgkit/package.json, packages/textkit/package.json, yarn.lock
some packages use `@babel/runtime`, but didn't have it in dependencies. this pr fixes that
=> chore: updated babel runtime and added it to all packages

.changeset/seven-buttons-joke.md, packages/textkit/src/engines/linebreaker/bestFit.js, packages/textkit/tests/engines/linebreaker/bestFit.test.js
Hi, I have been experiencing a weird issue related to how `applyBestFit` handles position. 
- [link to bestFit.js](https://github.com/diegomura/react-pdf/blob/3bcb031858062ca12865de7513c5fb5eb6ab3e4f/packages/textkit/src/engines/linebreaker/bestFit.js)
As you see, the current `applyBestfit` function suddenly stops getting `nextBreakPoint`.
I think this issue occurred because of the two lines. 
1. `getNextBreakpoint` returning null, when it shouldn't
```
if (sum.width - sum.shrink > lineLength) break; // getNextBreakpoint. 
```
In the function, when `sum.width - sum.shrink` is bigger than `lineLength`, it breaks. However, because the default value of position is `null`, in some cases, it just returns `null`. 
It is problematic because it means that after any node that has a width bigger …
=> Fix bestFit breakpoint issue

.changeset/empty-zoos-live.md, packages/stylesheet/package.json, packages/stylesheet/src/expand/boxModel.js, packages/stylesheet/src/expand/index.js, packages/stylesheet/src/expand/margins.js, packages/stylesheet/src/expand/paddings.js, packages/stylesheet/tests/expand.test.js, packages/stylesheet/tests/resolve.test.js, yarn.lock
Here is the first step for a stricter style parser. The current one ignores all edge cases and `@react-pdf/render` fails with crazy unpredicted errors. I use `postcss-value-parser` to achieve that, this is an internal package from `post-css` that parse all possible CSS values to `AST`. it introduces other opportunities, like `background` style support or maybe `calc` support
I rewrite box model parsing (margin/padding) to a new approach in this PR. it now 
- auto works properly in all cases ( `2 auto` or `1 auto 2 3` )
- auto works only with margin
- checks units for margin and padding
- ignores all invalid values
@diegomura @izmaelmag what do you think about these changes? what does `@react-pdf` should do with invalid values in the best scenario? (ignore, log errors, throw errors)
=> feat(stylesheet): rework box model style parsing

.changeset/poor-camels-listen.md, packages/pdfkit/rollup.config.js
=> fix: proper ignore node `fs` package in browser bundle

.changeset/hip-trainers-tickle.md, packages/renderer/index.d.ts
The old return type was `string` which is wrong, because it returns a `promise` which resolves in a `string` instead.
This pull request fixes the warning `'await' has no effect on the type of this expression` when using it like this:
```ts
const document = await ReactPDF.renderToString(...)
```
=> fix: define renderToStream to return promise

.github/CONTRIBUTING.md
As I was working to get setup to contribute, I followed the instructions in the contribution guide. I didn't previously have `lerna` so I first had to run `yarn install` before I could `yarn bootstrap`.
=> Instruct contributors to install before bootstrap

README.md
I believe `assert` should be the right key for the configuration object?
=> docs: fixed typo in webpack 5 config

.changeset/lazy-rules-attend.md, packages/fns/castArray.js, packages/fns/compose.js, packages/fns/reverse.js, packages/layout/src/steps/resolveStyles.js, packages/stylesheet/package.json, packages/stylesheet/src/expand/borders.js, packages/stylesheet/src/flatten/index.js, packages/stylesheet/src/index.js, packages/stylesheet/src/mediaQueries/index.js, packages/stylesheet/src/transform/colors.js, packages/stylesheet/src/utils/castFloat.js
Related to https://github.com/diegomura/react-pdf/pull/1827
Gradually start removing ramda. Although I like it, it's probably confusing for most people, it's slow and adds unneccesary bundle size. Some helper fns will still be needed. For the moment I moved them to utils dir, in the future it worths building our own set of light and reusable utils
=> refactor: remove ramda from stylesheet package

.changeset/green-mangos-begin.md, packages/svgkit/package.json, packages/svgkit/src/utils/getPageSize.js
Gradually start removing ramda. Although I like it, it's probably confusing for most people, it's slow and adds unneccesary bundle size. Some helper fns will still be needed. For the moment I moved them to utils dir, in the future it worths building our own set of light and reusable utils
=> refactor: remove ramda from svgkit

.changeset/great-candles-retire.md, packages/renderer/package.json
Gradually start removing ramda. Although I like it, it's probably confusing for most people, it's slow and adds unneccesary bundle size. Some helper fns will still be needed. For the moment I moved them to utils dir, in the future it worths building our own set of light and reusable utils
=> refactor: remove unused ramda dependency from renderer

.changeset/khaki-tomatoes-live.md, packages/unicode-properties/generate.js, packages/unicode-properties/index.js
Encodes trie data as base64 instead of raw buffer to reduce package size. Based on some quick estimations this reduces `@react-pdf/unicode-properties` size by half (from ~40kb to ~20kb). It's not much but every kb counts to reduce the lib overall bundle size
=> refactor: encode unicode trie as base64

packages/types/style.d.ts
Reverts https://github.com/diegomura/react-pdf/pull/1755
I'll remove that style from the site once published
=> fix: remove not supported type

.changeset/selfish-planets-arrive.md, packages/primitives/package.json
I forget to add the lib folder with CommonJS build to published files
fix #1844
=> fix: publish primitives packages as CommonJS

.changeset/warm-mangos-learn.md, packages/render/package.json, packages/render/rollup.config.js
`@react-pdf/render` was only being published as a CJS module, causing the wrong resolution of `normalize-svg-path` [here](https://github.com/jkroso/normalize-svg-path/blob/master/package.json#L13-L14) on webpack 5. 
Fixes #1831
=> feat: build render package as ES module

.changeset/cuddly-kiwis-pump.md, packages/layout/src/index.js, packages/layout/src/steps/resolveBookmarks.js, packages/layout/src/steps/resolvePagination.js, packages/layout/tests/steps/resolveBookmarks.test.js, packages/pdfkit/src/document.js, packages/pdfkit/src/mixins/outline.js, packages/pdfkit/src/outline.js, packages/render/src/index.js, packages/render/src/operations/addBookmarks.js, packages/types/bookmark.ts, packages/types/node.d.ts
Add bookmarks support. Bookmarks can be added by the `bookmark` prop on any component. Prop value can be either
- String, defining the bookmark title
- Object, with the following keys
- title: mandatory. Bookmark title
- top: optional. x coordinate to redirect bookmark. defaults to element top coordiante
- left: optional. y coordinate to redirect bookmark. defaults to element left coordinate
- fit: optional. redirect bookmark to page (0,0) coordinate
- zoom: optional. change zoom on bookmark redirect
- expanded. optional. all of that section's children will be visible by default 
Fixes #237
=> feat: bookmarks support

.changeset/honest-cars-carry.md, packages/pdfkit/src/document.js, packages/pdfkit/src/utils/capitalize.js, packages/renderer/src/index.js, packages/types/node.d.ts
Add `pageLayout` prop to Document. This controls how (some) PDF viewers choose to show pages
Values are
- singlePage: Display one page at a time
- oneColumn: Display the pages in one column
- twoColumnLeft: Display the pages in two columns, with odd numbered pages on the left
- twoColumnRight: Display the pages in two columns, with odd numbered pages on the right
- twoPageLeft: Display the pages two at a time, with odd-numbered pages on the left
- twoPageRight: Display the pages two at a time, with odd-numbered pages on the right
=> feat: add page layout support

.changeset/lucky-wombats-smoke.md, packages/pdfkit/src/document.js, packages/pdfkit/src/mixins/outline.js, packages/renderer/src/index.js, packages/types/bookmark.d.ts, packages/types/node.d.ts
Add `pageMode` prop to Document. A name object specifying how the document should be displayed when opened
Values are
- useNone: Neither document outline nor thumbnail images visible
- useOutlines: Document outline visible
- useThumbs: Thumbnail images visible
- fullScreen: Full-screen mode, with no menu bar, window controls, or any other window visible
- useOC: Optional content group panel visible
- useAttachments: Attachments panel visible
=> feat: add page mode support

.changeset/pretty-jars-begin.md, packages/layout/src/page/getSize.js, packages/layout/src/steps/resolveStyles.js, packages/pdfkit/src/page.js, packages/render/src/primitives/renderPage.js, packages/stylesheet/src/transform/units.js, packages/types/node.d.ts
Adds optional `dpi` prop to `Page` primitive
**Why Page and not Document?**
So the same document can have different DPIs in different pages
**What this prop does under the hood**
- Resizes page dimensions to match new dpi 
- Setup PDF page `UserUnit` field to dpi/72 
Reading at the PDF spect it seems that the latter point is the way to go, but I haven't seen any change in how readers (specially Adobe) renders pages or shows page dimensions. Seems like it's being ignored as far as I saw. But hopefully this will work for anyone requiring to have variable dpi.
Please open a new issue if someone trying this finds something not working as expected 
Fixes #1066
=> feat: variable dpi

packages/render/rollup.config.js
- remove minified build because nobody uses it and it takes so much time to compile.
- exclude `@babel/runtime` from the final bundle, it has weird imports like `@babel/runtime/**` so default approach with `Object.keys(pkg.dependencies)` doesn't work.
=> chore(render): tweak rollup config

.changeset/old-bottles-end.md, packages/layout/src/steps/resolveStyles.js, packages/layout/tests/steps/__snapshots__/resolveStyles.test.js.snap, packages/layout/tests/steps/resolveStyles.test.js
default link style overwrote user ones in the case with an array
[repl](https://react-pdf.org/repl?code=3187b0760ce02e00408a057025803c450298c0bc300500943807cf805030c00f0022230080b6198531165d400a02180e659a004f003619b006f61622003a0046200099080beed3a72a006491800d631a78891330a2834328004e3ca127000b86007230e032b803431408901b175779111e607d1f18461e1b3e3d1700460026557500090c1100aa007a5d030d4d6a02c36349006d330c0b2b5b7b4730608f302f5f7f40e0d0f0c8d55f0918b8849814d5005d0cac9cfcbd7d22ca3cde0122bcba0666567602006e323250485863081c18006528510c33800b0c0c2859601b0c7b0c3c090e4515174fcd00071e128947a3e0005440ff170019800acde0e25101c0d040085d050102305c00367862260c890580f8e940920005ee0280f04430fc6515464550ecf6002557b00a05c1a000c5642f3012830363c15110a87416172c456500)
=> fix: overwrite default styles in link component

.changeset/long-years-cry.md, packages/textkit/src/layout/generateLineRects.js, packages/textkit/src/layout/layoutParagraph.js, packages/textkit/src/rect/crop.js, packages/textkit/src/rect/intersects.js, packages/textkit/src/rect/partition.js, packages/textkit/tests/rect/intersects.test.js, packages/textkit/tests/rect/partition.test.js
Supports passing an array of `excludedRects` to `textkit.layoutText` function to support elements wrapping text via the `float` CSS property
=> feat: exclude rects on textkit layout container

.changeset/strange-pots-push.md, packages/layout/src/svg/layoutText.js, packages/layout/src/text/fromFragments.js, packages/layout/src/text/getAttributedString.js, packages/layout/src/text/layoutText.js, packages/layout/src/text/linesWidth.js, packages/layout/tests/text/fromFragments.test.js, packages/layout/tests/text/layoutText.test.js, packages/render/src/primitives/renderSvgText.js, packages/render/src/primitives/renderText.js, packages/textkit/babel.config.js, packages/textkit/package.json, packages/textkit/rollup.config.js, packages/textkit/src/index.js, packages/textkit/src/layout/finalizeFragments.js
Different approach of some of the work in https://github.com/diegomura/react-pdf/pull/1891 for building textkit. I'll rebase shortly
Builds textkit with rollup and defines a public api, so consumers do not import from `/lib`
Publishing it separately so I can remove `@react-pdf/unicode-properties` and go back to mainline repo
=> feat: build textkit with rollup & define public api

.changeset/silly-rice-chew.md, packages/renderer/index.d.ts, packages/renderer/src/dom/PDFDownloadLink.js
Based on request #975 and our own experience, having an `onClick` handler to invoke for `PDFDownloadLink` would be benficial. E.g. We'd like to send a custom event to our analytics on download. (We're finding other means to lazily load the heavier components, so wouldn't need to resort to the workaround for this feature [proposed there](https://github.com/diegomura/react-pdf/issues/975#issuecomment-674261430).)
This implementation refactors the existing `onClick` handler slightly, to also allow consumer's to provide a function via props. We conditionally call this function after existing `handleDownloadIE`. (We'd generally opt for `onClick?.()`, but as this package targets Node v12, we'll check `typeof` before invoking.)
I've included the `event` as the first function argument, should the …
=> feat: add onClick event to PDFDownloadLink

.changeset/cuddly-dolls-burn.md, packages/font/src/font.js, packages/font/src/index.js, packages/font/tests/font.test.js
Originally submited in https://github.com/diegomura/react-pdf/pull/1897
Couldn't add changeset to the original fork. Sorry @cexoso. Not really sure what I did wrong
=> fix: font store load method skip loading

.changeset/fifty-boxes-argue.md, packages/textkit/src/layout/layoutParagraph.js, packages/textkit/tests/layout/layoutParagraph.test.js
Bug was introduced in #1895
Error message: TypeError: rect2 is undefined (or similar)
In case there is no rect left for the text to flow to, we have to stay in the last one and overflow its bottom.
=> fix: console error when text overflows the last available rect

.changeset/soft-ladybugs-yell.md, packages/pdfkit/package.json, packages/renderer/package.json, packages/renderer/src/index.js, yarn.lock
There's no need to actually have this. We can just use pdfkit document stream to convert blob directly, which enables not having to polyfill stream just for blob creation in #1891
=> feat: remove blob stream dependency

.changeset/fresh-moons-cheer.md, packages/pdfkit/package.json, packages/png-js/package.json
Both packages, `pdfkit` and `png-js` are distributed with MIT license. This PR  adds an entry into each packages `package.json` file.
Hit me up if something is missing.
Thanks for the work @diegomura !
=> chore: adds missing licenses to package.json

packages/image/src/resolve.js
Hi,
this is a Hotfix for #1805.
It will disable caching for images from a buffer, until someone comes up with a better solution.
=> Hotfix: issue #1805 by not using the cache for images from a buffer

.changeset/stale-needles-wait.md, packages/layout/src/node/createInstance.js, packages/layout/src/node/createInstances.js, packages/layout/src/steps/resolvePagination.js, packages/renderer/tests/node.test.js
This change fixes #1872 by supporting fragments and arrays as valid nodes to be returned from `render`. It also adds support for nested dynamic components.
=> fix: TypeError when returning fragments or arrays from render prop

.changeset/tall-eggs-destroy.md, packages/layout/src/steps/resolvePagination.js, packages/layout/tests/steps/resolvePagination.test.js
This fixes `<Page wrap={false}>` not actually preventing a page from breaking. It also can save large amounts of time (I noticed a 50% performance increase) on pages with many elements.
=> fix: page wrap=false not preventing page from breaking

.changeset/tiny-needles-sing.md, packages/renderer/index.d.ts, packages/types/index.d.ts
**Addresses [1957](https://github.com/diegomura/react-pdf/issues/1957)**
Updates the typescript definitions for the Page component to include missing prop types: `dpi` and `bookmark`.
We're needing to use the `dpi` prop for our Typescript project so wanted to put in a quick fix for this issue!
=> Add missing `dpi` and `bookmark` page prop types

.changeset/funny-gifts-grin.md, packages/renderer/package.json, packages/renderer/rollup.config.js, packages/renderer/src/renderer.js, yarn.lock
I found a way to test it. 
npm supports installations from the tar archive, so I bundle a `@react-pdf/renderer` with those changes to a tar file with `npm pack` command and install into some new project
- The current master fails with error: 
```
npm i ./react-pdf-renderer-3.0.3.tgz
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-peer-deps@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6 || ^17.0.0" from @react-pdf/renderer@3.0.3
npm ERR! node_modules/@react-pdf/renderer
npm ERR!   @react-pdf/renderer@"file:react-pdf-renderer-3.0.3.tgz" from the root project
npm ERR! 
npm ERR! Fix …
```
=> bundle react-reconciler to avoid peerDeps problem

.changeset/young-students-allow.md, packages/renderer/index.d.ts
Fixes issues with conflicting or redundant `children` type definitions. 
I've included some history here to explain the issue as I understand it, what has been done to address it, and what is needed to fix the outstanding issues.
As mentioned in #1798, the release of react@18 [removed the implicit `children` prop](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210). It appears that the [types-react-codemod](https://github.com/eps1lon/types-react-codemod#readme) was used which added `React.PropsWithChildren<>` to all components. While this works for the majority of components, there are a few (`BlobProvider`, `PDFViewer`, and `PDFDownloadLink`) which have more specific requirements for `children`. The addition of `React.PropsWithChildren` with the existing definitions of …
=> Removed conflicting or redundant children props

.changeset/moody-bottles-buy.md, packages/layout/src/steps/resolvePagination.js, packages/layout/tests/steps/resolvePagination.test.js
Fixes problem described in #2197. I've tested it locally with [repro](https://react-pdf.org/repl?code=3187b0760ce02e0040a200f021816c00e01b0298c0bc3002804a3c03e420281860078011118015c52cc294abada005240731cd0027b65c01bdc5a24004c6404b30fc0170c004c001800d0c0046498006b7e009c4133032030880c204ea804419e7f0016514d6618e02fafce6e6e71006d00461d35005d003a1424340262324a20a0807a002a180015377908180037792c0077186024300072583724229c329304890033240c082c5f1d5d2c2aa61e9879769808457e6c4afc8c1951c2a45d19f6f958701828371c69411800491832ead828101834265875ad9d932c18984cf4ae34da0035528a9131491878899f88a0010880a0e7142a8d400561d348e4535500199b47a03318cc166b2d9ec4e00310c861000e003b1931cd47f0c102ef6e0d0bee563ab4d01d2e8f57c1328288b01271195e4326d938c21a0d001491c3a1dab83c28b17f431a6732586c76070c11cf8b26e98944a94029040d078321d …
=> Break on containers whose children can not fit on a page

.changeset/forty-forks-divide.md, packages/renderer/index.d.ts
fix issue #2231 
I added types in the correct file and it work properly
=> fix: Add missing props types on Document element

.changeset/silent-flowers-dream.md, packages/render/src/operations/transform.js
Providing one value to `translate()` produces valid SVG and is a common thing to see especially in minified SVGs.
When working with such SVG, I got a crash with a rather cryptic error message: "Error: unsupported number: undefined". Upon investigation, the lack of default `y` value turned out to be the cause.
=> fix: fix crash on `transform="translate(1)`

.changeset/cyan-keys-sing.md, packages/types/font.d.ts
When working on the PDF, I wrote the following code:
```ts
Font.register({
family: 'Helvetica Neue',
fonts: [
{ src: helveticaNeueRegular },
{ src: helveticaNeueMedium, fontWeight: '500' },
{ src: helveticaNeueBold, fontWeight: '700' },
],
});
const styles = StyleSheet.create({
foo: {
fontFamily: 'Helvetica Neue',
fontWeight: 500,
}
});
```
To my surprise, this did not work properly. After investigation, I figured out that my mistake was in defining `fontWeight` as string in `Font.register`, which is something TypeScript was okay with me to do.
Narrowing `fontWeight` type fixes that.
=> fix: fix all strings allowed in `fontWeight` in `Font.register`

.changeset/four-shirts-refuse.md, packages/image/src/resolve.js, packages/image/tests/resolve.test.js, packages/types/image.d.ts
**Description of change:**
Added `credentials` option which is required in `fetch` in order to send cookies in cross-origin requests.
src:[ mdn web docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
This PR also fixes the issue #1412
=> fix: allow credentials option in Image

.changeset/seven-dodos-live.md, packages/pdfkit/package.json, yarn.lock
Resolves #2447
Per https://nvd.nist.gov/vuln/detail/CVE-2023-46233 , `crypto-js` has a "critical" weakness in one of its algorithms, PBKDF2 .
`@react-pdf/pdfkit` has `crypto-js` as one of its dependencies, although it doesn't actually use the vulnerable algorithm, (it only uses `md5`). ( See https://github.com/diegomura/react-pdf/issues/2447#issuecomment-1811849815 ) 
SCA tools like dependabot don't perform static analysis to confirm that a given dependency's vulnerable code is actually used in a package, so even though react-pdf is not actually vulnerable, dependabot and other SCA tools will raise an alert.
=> build: update crypto-js from 4.0.0 -> 4.2.0 [CVE-2023-46233]

packages/renderer/index.d.ts
Vite.js is unable to build with the onClick attribute type of the ReactPDFDownloadLink function.
```bash
node_modules/@react-pdf/renderer/index.d.ts(451,15): error TS2552: Cannot find name 'function'. Did you mean 'Function'?
```
Suggested fix
```javascript
interface PDFDownloadLinkProps {
document: React.ReactElement<DocumentProps>;
fileName?: string;
style?: Style | Style[];
className?: string;
children?:
| React.ReactNode
| ((params: BlobProviderParams) => React.ReactNode);
onClick?: () => void; // 👈 Function void
}
```
=> fix: interface PDFDownloadLinkProps attribute onClick

.changeset/eighty-lizards-leave.md, packages/types/svg.d.ts
Using the clipPath attribute was causing a type error in Typescript because it was missing from the type def.
=> fix: add clipPath to typing for SVGPresentationAttributes

.changeset/pretty-flies-clean.md, packages/font/src/index.js, packages/layout/src/text/emoji.js, packages/types/font.d.ts
=> feat: add withVariationSelectors option to registerEmojiSource

.changeset/sharp-mirrors-taste.md, packages/layout/src/text/emoji.js
This PR fixes an issue where text fragments containing a special case symbol (trademark/copyright symbol) would get replaced with just the symbol. It also adds a new excluded symbol (™).
=> feat: include text preceeding special case emojis, include ™ symbol in excluded emojis

.changeset/brown-houses-count.md, packages/primitives/package.json
In #2409 I missed changing the extension of CJS code to .cjs, resulting in (inaccurate) ERR_REQUIRE_ESM error thrown in Node in CJS environment.
=> fix: fix require @react-pdf/primitives from CJS

.changeset/tidy-houses-sleep.md, packages/examples/src/objectFit/index.jsx
There's no display: block in react-pdf, only flex or none.
=> fix: fix invalid display property in objectFit example

.changeset/pretty-moons-hang.md, packages/renderer/index.d.ts
Examples show that this is totally fine:
https://react-pdf.org/repl?example=lineargradient
https://react-pdf.org/repl?example=radialgradient
=> fix: props unnecessarily required in LinearGradient and RadialGradient in TypeScript

packages/pdfkit/src/path.js
Types references were copied from the original repository, but type definitions were not. This fixes that.
=> fix: add missing types for parseDataPath function

.changeset/wet-glasses-tickle.md, packages/renderer/index.d.ts
These are still missing in the renderer, so adding them.
In general, `renderer/DocumentProps` should extend from `types/DocumentProps` ideally, but that will be a larger refactor task
=> fix: creationDate and modificationDate types

.github/workflows/main.yml, .github/workflows/release.yml, package.json, yarn.lock
This PR revamps GitHub Actions workflows.
What was done:
- All actions used were bumped to their latest versions to ensure no deprecation warnings are being shown.
- Split workflows into multiple jobs, so e.g. checking size can run only once, but unit tests - multiple times, which brings me to…
- Unit tests were configured to run on multiple versions of Node.js (18 and 20).
- Other jobs were bumped to run on Node.js 20 instead of 18.
- Added `--frozen-lockfile` to install command to ensure no changes are being sneaked in.
- Set up Yarn cache to speed up CI process
While the total CI run time is significantly increased (we're doing far more testing than we used to), the overall CI duration has _decreased_, because all jobs are running in parallel and additional optimizations were done to …
=> chore: split GitHub Actions workflows into jobs; run tests on multiple Node.js versions

.prettierignore
By ignoring /lib/, time it takes on my machine to run Prettier on the entire repo falls from 8.5 to 2.95s.
=> chore: do not run Prettier on /lib/

packages/image/package.json, packages/image/src/jpeg.js, packages/pdfkit/package.json, packages/pdfkit/src/image/jpeg.js, yarn.lock
Fixes: https://github.com/diegomura/react-pdf/issues/2535
Fixes: https://github.com/diegomura/react-pdf/issues/2574
Wrote a JPEG decoder [here](https://github.com/diegomura/jay-peg) that's very performant and leverages restructure which is already used in the project, so it should not add much bundle size (maybe it will even reduce it). This does more than getting EXIF data, so maybe in the future can be used to embed extra info of the image in the document. This should fix the node dep errors people are getting out of `jpeg-exif`
=> fix: replace jpeg-exif with jay-peg

.changeset/serious-teachers-join.md, packages/fns/src/index.js, packages/fns/src/repeat.js, packages/fns/tests/repeat.test.js, packages/image/src/resolve.js, packages/layout/src/svg/layoutText.js, packages/layout/src/text/getAttributedString.js, packages/layout/src/text/layoutText.js, packages/pdfkit/src/font/embedded.js, packages/textkit/package.json, packages/textkit/src/attributedString/fromFragments.js, packages/textkit/src/engines/bidi/index.js, packages/textkit/src/glyph/slice.js, packages/textkit/src/index.js, packages/textkit/src/layout/applyDefaultStyles.js, packages/textkit/src/layout/bidiMirroring.js, packages/textkit/src/layout/bidiReordering.js, packages/textkit/src/layout/generateGlyphs.js, packages/textkit/src/layout/index.js, packages/textkit/src/layout/preprocessRuns.js, packages/textkit/src/layout/wrapWords.js, packages/textkit/tests/engines/bidi.test.js, packages/textkit/tests/internal/bidiEngine.js, packages/textkit/tests/layout/bidiMirroring.test.js, packages/textkit/tests/layout/bidiReordering.test.js, packages/textkit/tests/layout/preprocessRuns.test.js, yarn.lock
Fixes #1571 
Fixes #1636
Fixes #933
Fixes #960
Fixes #1394
Fixes #747
Fixes #856
Mirror of https://github.com/diegomura/react-pdf/pull/1485
Mirror of https://github.com/diegomura/react-pdf/pull/1821
All props should go to @ahmed-novalabs really. He continued my work on this topic. His fork ended up having tons of conflicts, and tried to rebase but just messed it up, sorry. If someone knows how can I rebase someone else's PR branch I'd appreciate it. Every time I mess it up. I'll add him as co-author though so PR should not matter that much. In here I was able to bring changes one by one while I also tested them.
I tested it and just by seeing glyphs I see them being rendered correctly, but I can't really read any rtl language to catch small bugs that might have, so any help will be …
=> feat: add bidi support

.changeset/curly-kings-exist.md, packages/fns/rollup.config.js, packages/font/rollup.config.js, packages/image/rollup.config.js, packages/layout/rollup.config.js, packages/png-js/rollup.config.js, packages/render/rollup.config.js, packages/renderer/rollup.config.js, packages/stylesheet/rollup.config.js, packages/textkit/rollup.config.js
Closes #2602
Closes #2603
Sorry about that!
We will also need some sanity checks to prevent this from happening in the future.
=> fix: fix CJS compatibility

.changeset/silver-poems-look.md, packages/pdfkit/rollup.config.js
Missed that one in #2607!
Closes #2608
=> fix: CJS compatibility in @react-pdf/pdfkit

.github/workflows/main.yml
Fixes an issue where .toUpperCase() was used in an expression that's not JS, causing an error.
Please kindly run this workflow against this branch - no other way to test it, and I can't trigger it myself.
=> fix: CI workflow error

.changeset/nasty-lemons-pump.md, packages/image/package.json, packages/pdfkit/package.json, yarn.lock
jay-peg 1.0.0 suffered from an issue that caused module resolution error in CJS mode.
=> fix: bump jay-peg dependency to fix CJS module resolution error

.changeset/wicked-jeans-switch.md, packages/pdfkit/src/image/jpeg.js
Fix https://github.com/diegomura/react-pdf/issues/2625
Implementing the improved fix off of the back of oogas pull request, and information from this [comment thread.](https://github.com/diegomura/react-pdf/pull/2646)
- By dynamically adapting to the actual bit depth, we avoid hardcoding 8 bits (which would limit quality for higher bit-depth images).
- Avoids `this.bits` being undefined, which was problematic in more strict PDF viewers such as Adobe, Mac Preview and Safari.
I had the time and wanted to trial the open source flow anyway (Feel free to decline this if this is overstepping someone else's work I'm not trying to take credit or anything, I am simply looking to get this fix rolled out ASAP as we are using it in a company project).
Trying to be helpful in expediting is all.
=> fix: jpeg precision metadata

.changeset/pretty-humans-add.md, packages/pdfkit/src/mixins/vector.js
This code previously required the values in stroke-dasharray to be greater than zero, but zero is actually a valid value. It can be used with stroke-linecap to create dotted lines. [See here](https://codesandbox.io/p/sandbox/blissful-hooks-kslsln?file=%2Fsrc%2FApp.js%3A17%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvb71ixw000620671ab81ot2%2522%252C%2522sizes%25 …
=> fix: support values of `0` in stroke-dasharray

.changeset/giant-adults-deny.md
We updated the `fontFamily` types in #2640 but forgot to bump the version of the types package.
=> Bump types package

packages/examples/src/fontFamilyFallback/index.jsx, packages/layout/src/text/fontSubstitution.js
Changes in #2640 caused a regression by not providing proper support for [font families made available within the library](https://react-pdf.org/fonts#register). This has caused any font families that are built-in to the library to default to Helvetica.
- Properly handles `run.attributes.font` as an array so any strings properly`getOrCreateFont` their associated fonts.
- Update the test page to include fonts made available within the library.
Issue: #2730
Before the change:
After the change:
=> fix: available Font Family Regression

.changeset/nine-ways-walk.md, packages/examples/src/fontFamilyFallback/index.jsx, packages/layout/src/text/fontSubstitution.js, packages/layout/tests/text/fontSubstitution.test.js
This recent change https://github.com/diegomura/react-pdf/pull/2640 appears to have caused a regression where the first font used in a line of text is utilized for the entire line. This includes usage of `fontFamily`, `fontWeight`, and `fontStyle`.
* Fixed `pickFontFromFontStack` to select from `fontStack` before `lastFont`. This should now properly prioritize fonts
* Added unit tests: `packages/layout/tests/text/fontSubstitution.test.js`
* Updated example document to include this scenario
* https://github.com/diegomura/react-pdf/pull/2640
* https://github.com/diegomura/react-pdf/issues/2730
* https://github.com/wojtekmaj/react-pdf/issues/1790
```
<Text style={{ fontSize: 10 }}>
The following are multiple font families, weights, and styles all on the
same line
</Text>
<Text style={{ …
```
=> fix: font selection regression

.changeset/pretty-jars-begin.md, packages/layout/src/page/getSize.js, packages/layout/src/steps/resolveStyles.js, packages/stylesheet/src/transform/units.js
Fix for dpi issue implemented with #1869
fixes #1953 
fixes #2006
fixes #2668 
Unfortunately was~~n't~~ able to get it linked locally so this is **~~untested~~ tested**. Maybe someone could test or have some tip how to get the package tested locally. I followed the steps in the CONTRIBUTION.md and it says it's linked but it does not detect changes using `yarn watch` and doesn't make any changes in my test setup. `yarn bootstrap` is not working for me but for my understanding also should not be needed anymore?
**Edit:** I was able to test this not in local development but in my build and it does the desired job.
- Set up PDF with `<Image style={{width: 100}} />` and `<Text style={{fontSize: 12}}/>` and some basic style. `<page size="A4">`
- Have a look at the result (it's with 72 dpi)
- …
=> fix: page dpi

packages/types/svg.d.ts
fix for the strokeLinecap type for SVGs
Closes #2707
=> fix: strokeLinecap type

.changeset/bright-ghosts-drum.md, packages/layout/src/yoga/index.js
This PR should fix the #2825 
It's not necessary to load and compile yoga-layout WebAssembly binaries more than once. 
https://github.com/facebook/yoga/issues/1320#issuecomment-1616187392
Current master is a bit broken but this is tested top of the [latest release commit](https://github.com/diegomura/react-pdf/commit/6bf9d990723db757232c42e3a040bbfaa5ceb308)
=> fix: load yoga binaries only once

.changeset/fair-rocks-leave.md, packages/layout/src/steps/resolvePagination.js, packages/layout/tests/steps/resolvePagination.test.js
The existing check for whether all children got moved the next page makes sense if we're already partly through the page - but if this happens before we have anything in `currentChildren` then we'll essentially leave a blank page and move everything to the "next" page, which results in an infinite loop (since the next page never gets smaller).
This PR checks for this situation, and in this case will add the current node to the current page and push the remaining nodes to the next page. This ensures that the next page will get smaller by at least one node so that future iteration won't infinitely loop.
I added a test case that reproduces it - the test doesn't fail it will just hang forever, but if it doesn't loop then the test will pass successfully.
Fixes …
=> fix: prevent infinite loop while splitting pages

.changeset/rare-moles-raise.md, packages/types/font.d.ts, packages/types/style.d.ts
#2640 Added support for font fallbacks, but we updated the types incorrectly.
`FontSource` should still accept just a `string`.
However, in stylesheets we should be able to specify an array of font families (as shown in the font fallbacks example [here](https://github.com/diegomura/react-pdf/blob/6bf9d990723db757232c42e3a040bbfaa5ceb308/packages/examples/src/fontFamilyFallback/index.jsx#L18)).
- Update `FontSource` and `Style` type declarations accordingly
- Bump `types` version
=> fix: font fallbacks types

packages/renderer/index.d.ts
Fixes #2623
This updates the types to follow the rules for using `export =`, wherein the exports need to be inside the namespace to preserve the rule that `export =` can be the only export.
=> fix: TypeScript types

.changeset/pink-owls-drum.md, packages/render/src/primitives/renderSvg.js
The check tested the existence of `renderFns` instead of `renderFn`.
=> fix: check SVG node type is not currently supported

.changeset/strong-rockets-fix.md, packages/fns/package.json, packages/fns/rollup.config.js, packages/font/package.json, packages/font/rollup.config.js, packages/image/package.json, packages/image/rollup.config.js, packages/layout/package.json, packages/layout/rollup.config.js, packages/pdfkit/package.json, packages/pdfkit/rollup.config.js, packages/png-js/package.json, packages/png-js/rollup.config.js, packages/primitives/package.json, packages/render/package.json, packages/render/rollup.config.js, packages/renderer/package.json, packages/renderer/rollup.config.js, packages/stylesheet/package.json, packages/stylesheet/rollup.config.js, packages/textkit/package.json, packages/textkit/rollup.config.js
For more details look at: https://github.com/diegomura/react-pdf/pull/2711#issuecomment-2366834537
=> feat!: drop cjs support

.changeset/slow-ravens-type.md, packages/layout/src/yoga/index.js
When quickly calling `loadYoga()` multiple times (in a script or web server that generates PDFs, for example), Yoga would try to initialize multiple times and eventually throw a strange error like:
`BindingError: Expected null or instance of Config, got an instance of Config`
Fixes #2892
=> fix: Prevent Yoga init from running more than once

packages/types/image.d.ts
`<Image src={{ uri: 'https://someurl.com/image.png', credentials: 'include' }}  />`should also be allowed by the type and not throw an error and (except the ts warning) is working as expected.
=> feat: update SourceURLObject Type

packages/types/style.d.ts
**What was changed**: Added the 'none' option to the textTransform property in the style interface.
**Reason for change**: This allows developers to explicitly set textTransform to 'none', which prevents any automatic capitalization or case changes. It provides more flexibility in text styling where no transformation is desired.
=> Fix: Add 'none' option to textTransform property in style interface

.changeset/nasty-bags-pay.md, packages/layout/src/text/emoji.js, packages/layout/src/text/fontSubstitution.js
This pull request proposes to add fallback to monochrome emojis if no emoji image source available. Though react-pdf does not support colour emojis yet, it is useful for monochrome or grayscale documents if we can fallback to the monochrome emojis.
=> feat: Use monochrome emojis contained in the font family if no emoji source available

.changeset/fifty-rockets-relax.md, packages/font/package.json, packages/font/setupTests.js, packages/font/src/font.js, packages/image/package.json, packages/image/src/resolve.js, packages/image/vitest.setup.js, packages/layout/package.json, packages/layout/setupTests.js, yarn.lock
Closes: #2925
Node 18 (lowest version we support) has native fetch support so it does no make any point to keep using `cross-fetch`
=> feat: remove cross-fetch

.changeset/tame-yaks-speak.md, packages/layout/src/text/getAttributedString.js, packages/stylesheet/src/transform/index.js, packages/stylesheet/src/transform/lineHeight.js, packages/stylesheet/tests/transform.test.js
=> feat: support multiple line-height units

.changeset/famous-kings-dress.md, packages/layout/src/steps/resolveStyles.js, packages/stylesheet/src/transform/units.js, packages/stylesheet/tests/resolve.test.js, packages/stylesheet/tests/transform.test.js
Base rem unit is `<Page />` font-size (not Document)
=> feat: support rem units

.changeset/sour-roses-draw.md, packages/reconciler/package.json
=> fix: add scheduler dependency

.changeset/wicked-apes-kick.md, packages/reconciler/package.json
=> fix(reconciler): missing dependencies

.changeset/long-elephants-cross.md, packages/reconciler/package.json, packages/reconciler/rollup.config.js, packages/reconciler/src/index.js, packages/reconciler/src/reconciler-23.js, yarn.lock
Fixes #2978
Fixes #2982
Fixes #2973
Fixes #2957
Rollback to reconciler v23 for React 16, 17 and 18, which is what we historically used. I bumped it on the latest changes thinking it would be fine, but apparently I need a change I ignore. There's no reason why not going back to this. Has been working great for many years. People will start migrating to React 19 eventually and this will get deprecated over time
=> fix: conditional rendering

.changeset/selfish-rivers-serve.md, packages/textkit/src/layout/layoutParagraph.js
Prepend width minus indentation instead of subtracting the indentation value in first entry of availableWidths.
In the linebreak algorithm, [a line length is determined by the length value provided in the lines array in a specific index](https://github.com/diegomura/react-pdf/blob/master/packages/textkit/src/engines/linebreaker/linebreak.js#L69) or by using the last item of the array, however most of the arrays provided when calling `layoutParagraph` have just a single value. By subtracting the indent from the first value in the array (which in most cases is also the last one) will make all lines that do not have a matching element in the array the same width, hence having a lot of extra whitespace on the right hand side when providing a value for indent.
Closes #2968
=> fix(textkit): make indentation only affect first line.

packages/font/src/font.js
It helps knowing if the error is general (wrong source path...), or just a specific like an italic font missing.
=> chore: be more specific on an error log

.changeset/neat-otters-jump.md, packages/renderer/index.d.ts
Fix #3012 
**Description:**
This pull request addresses the TypeScript error `TS2769: No overload matches this call` that occurs when using `PDFDownloadLink` as described in issue [#3012](https://github.com/diegomura/react-pdf/issues/3012).
**Changes:**
- Updated the type definitions for `PDFDownloadLink` to correctly accept the child render function.
- Adjusted the implementation to align with the expected types.
**Steps to Reproduce:**
1. Use `PDFDownloadLink` with the following setup:
```tsx
import { PDFDownloadLink } from '@react-pdf/renderer';
const MyDocument = () => (
<Document>
<Page>
<Text>Hello, world!</Text>
</Page>
</Document>
);
const DownloadLink = () => (
<PDFDownloadLink document={<MyDocument />} fileName="example.pdf">
{({ loading }) => (loading ? 'Loading...' : 'Download …
```
=> fix: PDFDownloadLinkProps Type Error

.changeset/witty-mugs-wash.md, packages/pdfkit/src/document.js, packages/pdfkit/src/mixins/pdfa.js, packages/pdfkit/src/mixins/pdfua.js, packages/pdfkit/src/mixins/subsets.js
One step closer to unify with `pdfkit` and remove our fork
=> feat: add pdfkit subsets mixin

packages/layout/src/svg/inheritProps.js, packages/layout/src/svg/layoutText.js
Fixes https://github.com/diegomura/react-pdf/issues/2931
If the `x` attribute of a `<tspan>` has not been defined explicitly, the current behavior causes the each `<tspan>` to inherit the `x` value of it's parent `<text>` element.
```js
<Svg>
<Text x="10" y="30">
<Tspan>One</Tspan>
<Tspan>Two</Tspan>
<Tspan>Three</Tspan>
</Text>
</Svg>
```
**Is**:
**Should**:
This PR fixes this issue by...
- resetting the inherited `x` value to the original `x` value of the `<tspan>`
- aggregating an offset for each children of a `<text>` node and using it as the child node's `x` value, if necessary
=> fix: calculate x position of tspan elements without explicit x prop

.changeset/stupid-waves-hunt.md, package.json, packages/pdfkit/babel.config.js, yarn.lock
Closes #3109
This should be valid syntax in all modern browsers and node versions, but let's add it as the lift is low. I might remove it in teh future or once we can use upstream pdfkit
=> feat(pdfkit): compile nullish coalescing operator
