examples/fractals/output.pdf, examples/fractals/styles.js, packages/react-pdf/src/elements/Text.js
This is not the fanciest way of dealing with defaultProps, but I created an issue for it (#47).
In the meantime, this will work just fine
=> Add fontSize support

examples/fractals/index.js, examples/fractals/output.pdf, packages/react-pdf/package.json, packages/react-pdf/src/elements/Document.js, packages/react-pdf/src/elements/Info.js, packages/react-pdf/src/utils/pdf.js, packages/react-pdf/yarn.lock
=> Add metadata to the pdf document

examples/fractals/index.js, examples/fractals/output.pdf, packages/react-pdf-node/src/index.js, packages/react-pdf/src/index.js
=> Add callback on Document and node mounter

packages/react-pdf/src/index.js
=> Fix stylesheet import for certain bundlers

examples/dom-bindings/package.json
This one is not tracked anymore by lerna and will removed in the future, once we have implemented the suggested approach in #62 is implemented.
=> Update package.json for the DOM example.

.travis.yml, lerna.json, package.json, packages/react-pdf-dom/package.json, yarn.lock
Looks like the last release candidate of lerna is freezeing the screen
on the instalation process. Move to the previous versions seems to work
fine.
Fixes #76
=> Fixed issue with lerna

examples/package.json, examples/yarn.lock, package.json, packages/react-pdf/package.json, packages/react-pdf/src/elements/Text.js, packages/react-pdf/yarn.lock
=> Fix dependencies

packages/react-pdf/src/elements/Link.js, packages/react-pdf/src/elements/index.js, packages/react-pdf/src/index.js
Created Link component that could be added in anypart of the page,
except with a Text component. That requires extra work to calculate the
place in the text the Link should go.
=> Adding basic support for Link component

packages/react-pdf-node/src/index.js
The stream wasn't finish when the callback was called that causes an
empty file to be returned.
Fixes #116
=> Wait until stream finshed to write the pdf

CONTRIBUTING.md
The relative hrefs tried to point to a file called `issues`.
=> Fix links to issues page in CONTRIBUTING.md

packages/react-pdf/src/elements/Page.js
=> Disable margins in Page element

packages/react-pdf/package.json, packages/react-pdf/src/elements/Base.js, packages/react-pdf/src/elements/Image.js, packages/react-pdf/src/elements/Link.js, packages/react-pdf/src/elements/Text.js, packages/react-pdf/src/mixins/borders.js, packages/react-pdf/src/utils/styles.js, packages/react-pdf/yarn.lock
=> Styles cascading

packages/react-pdf/src/renderer.js
=> Fix typo in commitTextUpdate()

packages/react-pdf/package.json, packages/react-pdf/yarn.lock
=> Upgrade yoga-layout

packages/react-pdf/src/elements/Text.js
**Orphans**
**Widows**
**Orphans**
**Widows**
=> Avoid orphans and widows

examples/resume/Experience.js
I made some spelling changes to fit with the theme for this mock resume. I also extracted the ExperienceEntry prop info into an array of objects and used .map to to render the components.
=> Update Resume Text and Use .map for Rendering ExperienceEntry Components

src/index.js
=> Pass relevant details about the document in onRender method

package.json, src/utils/attributedString.js, yarn.lock
Fixed by @asmockler. Thank you!
Fixes #241
=> Add letterspacing support

src/elements/Page.js, tests/layout.test.js, tests/note.test.js
=> Make page wrap default

src/elements/Document.js, tests/document.test.js
The string on the TextInstance node is on the value property. As a result, emojis where not loaded before the rendering.
=> Fix loading available emojis

package.json, rollup.config.js, src/elements/Document.js, src/elements/Image.js, src/elements/Node.js, src/elements/Page.js, tests/layout.test.js, yarn.lock
=> Enable images as dynamic render nodes

package.json, src/elements/Base.js, src/elements/Node.js, src/elements/Page.js, src/utils/attributedString.js, src/utils/matchPercent.js, src/utils/upperFirst.js, tests/node.test.js, tests/utils/polyfills.js, yarn.lock
=> Support percentage paddings on Page

src/utils/attributedString.js, src/utils/capitalize.js
=> Fix textDecoration capitalize

src/elements/Base.js, src/elements/Node.js, src/renderer.js, tests/node.test.js
=> Add insertBefore method to renderer

src/elements/Base.js, src/elements/Document.js, src/elements/Page.js, src/elements/TextInstance.js, src/index.js, tests/pdf.test.js
=> Return layoutData onRender

src/dom.js, src/font/index.js, tests/font.test.js, tests/utils/setupTests.js
Fixed https://github.com/diegomura/react-pdf/issues/431:
- Fixed problem with infinite rerendering on error
- Added better error message for invalid font url in browser environment
=> Fixed page hangs on error

src/elements/Root.js, src/elements/TextInstance.js, src/renderer.js, src/utils/propsEqual.js, tests/propsEqual.test.js
=> Fix update issues

src/utils/matchPercent.js
=> Negative percentage support

src/layout/linebreaker/index.js
=> Fix linebreaking

src/dom.js
=> Add innerRef prop to PDFViewer

src/elements/Image.js
=> Enhance Image measure function

package.json, src/elements/Text.js, src/elements/TextInstance.js, tests/text.test.js, yarn.lock
=> Fix text align

index.d.ts
=> Fix type for toBlob to Promise

.eslintrc, index.d.ts, jest.config.js, package.json, rollup.config.js, src/elements/Image.js, src/elements/Text.js, src/elements/TextInstance.js, src/font/index.js, src/utils/cache.js, src/utils/image.js, tests/cache.test.js, tests/font.test.js, tests/image.test.js, tests/layout.test.js, tests/text.test.js, tests/utils/setupTests.js, yarn.lock
=> Fetch headers

src/elements/Base.js, src/mixins/debug.js, src/mixins/transform.js, src/stylesheet/transformOrigin.js, src/stylesheet/transformStyles.js, src/stylesheet/transformUnits.js, tests/styleShorthands.test.js, tests/stylesExpansion.test.js, tests/transform.test.js
=> Add transformOrigin support

src/layout/linebreaker/index.js
=> Fix ligatures at the end of paragraph

package.json, src/elements/Image.js, tests/image.test.js, yarn.lock
Components styled with `styled-components`, for reasons I don’t currently know 😉, seem to have their `style` prop passed in inside an array. To resolve this I have made the `Image` component take its `objectFit` property from `this.style` instead of `this.props.style`.
=> Apply objectFit styling correctly

src/renderer.js, src/utils/url.js, tests/url.test.js
Allow links such as `skype:username`
=> Add skype links

src/elements/Image.js, src/elements/Page.js
=> Dynamically update Page size and orientation

package.json, yarn.lock
=> Bump hyphen

src/utils/attributedString.js
=> Add text decoration line-through support

src/utils/deepMerge.js
=> Gracefully handle undefined styles

package.json, src/utils/attributedString.js, yarn.lock
=> Add text-indent support

src/layout/fontSubstitution/standardFont.js
=> Fix standard font vertical align

src/elements/Document.js, src/utils/attributedString.js
=> Add inline image support

package.json, src/layout/fontSubstitution/index.js, src/utils/attributedString.js, yarn.lock
=> Fix non-latin language text rendering

package.json, src/elements/Text.js, tests/text.test.js, yarn.lock
=> Add maxLines and ellipsis support

src/elements/Text.js
=> Fix text layout

package.json, yarn.lock
=> Fix leading soft-hyphens

src/elements/Base.js, src/elements/Document.js, src/elements/Image.js, src/elements/Page.js, src/stylesheet/transformUnits.js, src/utils/pageSizes.js
Docs updated as well via [this PR](https://github.com/react-pdf/site/pull/20).
=> Add support for page auto height

src/elements/Document.js
=> Fix Page deletion

.travis.yml, package.json, src/renderer.js
Essentially copied the fix from the [ink repo](https://github.com/vadimdemedes/ink/blob/d30e4c8f1a681d6620669eea81f680efede211a5/src/create-reconciler.js)
References:
https://github.com/diegomura/react-pdf/issues/557
=> schedulePassiveEffects is not a function

src/elements/Node.js
=> Fix setPointScaleFactor

src/elements/Image.js
I use this to do some image processing. It is not intended to be merged as is, but rather to discuss if such a feature should be added to the package.
Let me know what you think !
=> Image fetching middleware

index.d.ts
https://github.com/diegomura/react-pdf/blob/1bc45ae3da2740eb008df8b1486454cd0753fe65/src/dom.js#L89-L95
=> Adds type for innerRef of PDFViewer

src/elements/View.js
These changes add support for `overflow: 'hidden'`
=> Add support for overflow

examples/fractals/README.md, examples/images/README.md, examples/knobs/README.md, examples/mediaQueries/README.md, examples/pageWrap/README.md, examples/text/README.md
The logo's path seemed to be wrong, so I fixed it 🔧
=> Fix logo source path

lerna.json, package.json, packages/font/src/font.js, packages/renderer/index.d.ts, packages/renderer/src/dom.js, packages/renderer/src/node.js, yarn.lock
Hi @diegomura as promised here are couple of changes I would like to get into v2:
=> V2 Enhancements

packages/layout/src/text/getAttributedString.js
Recursive call to getFragments had wrong arguments
=> fix(layout): Fix bug in getAttributedString

packages/render/package.json, yarn.lock
Hey @diegomura I've run into same issues when trying to generate a SVG with gradients:
https://github.com/jkroso/normalize-svg-path/issues/4
Bump fixes it 😏
=> Bumb normalize svg path

packages/font/src/font.js
This was causing font registration to fail
=> fix(v2): bug with registering font families

src/layout/fontSubstitution/index.js
=> Fix letter spacing for inline text elements (issue #644)

README.md
Mirrors changes in @wojtekmaj's react-pdf README: https://github.com/wojtekmaj/react-pdf/commit/4073a31bf2bba6e48cf09e799d8f6f861cc92eac
=> Add section on @wojtekmaj's react-pdf for lost souls in README

index.d.ts
=> Remove ts reference

packages/layout/package.json, packages/render/package.json, packages/renderer/index.d.ts, yarn.lock
=> Rollback textkit update

packages/layout/package.json, packages/layout/src/text/layoutText.js, packages/render/package.json, yarn.lock
=> Fix hyphenation valueOf odd behaviour

packages/stylesheet/src/expand.js, packages/stylesheet/src/resolve.js, packages/stylesheet/tests/expand.test.js, packages/stylesheet/tests/resolve.test.js
=> Fix margin and padding auto

packages/layout/src/steps/resolveAssets.js
=> Fix missing ramda function

packages/layout/src/steps/resolvePagination.js
=> Fix wrap=false element infinite loop

packages/stylesheet/src/expand.js, packages/stylesheet/tests/expand.test.js, packages/stylesheet/tests/resolve.test.js
=> Fix negative margin and padding support

packages/layout/src/page/getContentArea.js
=> Fix page wrapping

packages/render/src/operations/transform.js
=> Fix transform rotate

packages/renderer/index.d.ts
This pull request adds an export of the Tspan component.
Fixes issue #1215
=> Add missing Tspan export

packages/renderer/src/dom.js
=> Fix BlobProvider usePDF document

packages/renderer/index.d.ts, packages/renderer/src/index.js
=> Add ability to specify PDF language

packages/font/src/font.js
Fixes #1220
@gabrielvincent I realized this was needed. So sorry about that. I ended up implementing it a bit differently and in a different place, and also fixed another small bug in the process. Thank you though!
=> Fix font weight processing

packages/stylesheet/src/expand.js, packages/stylesheet/tests/resolve.test.js
=> Fix flex basis parsing

packages/renderer/index.d.ts
=> Remove types circular reference

packages/fontkit/src/tables/GPOS.js
=> Fix fontkit table issue

packages/pdfkit/src/mixins/text.js, packages/pdfkit/src/page.js, packages/render/src/index.js, packages/render/src/primitives/renderDebug.js
=> fix: debug prop

packages/layout/src/text/getAttributedString.js, packages/render/src/index.js, packages/render/src/primitives/renderBackground.js, packages/render/src/primitives/renderText.js, packages/render/src/utils/parseColor.js, packages/render/tests/utils/parseColor.test.js, packages/textkit/src/layout/applyDefaultStyles.js, packages/textkit/tests/layout/applyDefaultStyles.test.js
=> feat: text rgba color support

packages/renderer/src/index.js
=> fix: revert refactor

packages/layout/src/text/standardFont.js, packages/textkit/src/block/truncate.js, packages/textkit/src/layout/typesetter.js
=> fix: ellipsis rendering

packages/layout/src/text/measureText.js, packages/render/src/primitives/renderNode.js, packages/render/src/primitives/renderText.js, packages/textkit/src/layout/finalizeFragments.js
=> fix: text align when inside center-justified content

packages/render/src/primitives/renderImage.js
=> fix paddingTop in image component

packages/stylesheet/src/index.js
=> fix: remove style none value filter

packages/layout/src/steps/resolveTextLayout.js, packages/render/src/primitives/renderText.js
=> fix: inline text rendering

packages/renderer/src/dom.js
=> fix: PDFViewer src while loading

packages/layout/src/steps/resolveSvg.js, packages/layout/src/svg/inheritProps.js, packages/render/src/operations/transform.js, packages/stylesheet/src/index.js, packages/stylesheet/src/transform/transform.js, packages/stylesheet/tests/transform.test.js
=> fix: SVG transform

packages/layout/src/index.js, packages/layout/src/steps/resolveLinkSubstitution.js, packages/layout/src/steps/resolveSvg.js, packages/layout/tests/steps/__snapshots__/resolveLinkSubstitution.test.js.snap
=> fix: link substitution step

packages/renderer/index.d.ts
=> types: convert type definitions to module

packages/render/src/primitives/renderBackground.js, packages/render/tests/primitives/renderBackground.test.js
This addresses #838
Let me know if this is the correct logic and I'll add some tests against it.
[Edit] updating tests and my fix.
=> fix issue with background color opacity never being selected

.github/workflows/main.yml, packages/renderer/tests/transform.test.js
=> chore(ci): setup github action

packages/fontkit/src/opentype/OTProcessor.js
=> fix: fontkit scoping issue on phase variable

.husky/pre-commit, package.json, yarn.lock
=> chore: update husky lint staged

.changeset/nervous-chefs-drum.md, packages/render/src/primitives/renderDebug.js
=> fix: skip margin auto in debug mode

.changeset/angry-bikes-allow.md, packages/layout/src/node/splitNode.js, packages/layout/tests/steps/resolvePagination.test.js
=> fix: use styles for forcing nodes height after split

.github/workflows/main.yml, packages/renderer/.size-limit.js, packages/renderer/package.json, yarn.lock
check the size of whole `@react-pdf/renderer` with all dependencies and polyfills
=> chore: add size-limit check

.changeset/heavy-masks-fly.md, packages/font/package.json, packages/image/package.json, packages/layout/package.json, yarn.lock
=> chore: bump cross-fetch

packages/types/page.d.ts
Add corresponding type for page size ID1 (https://github.com/diegomura/react-pdf/pull/1033)
=> Minor Fix - Add ID1 type

packages/renderer/index.d.ts
Proposed solution to issue #1811.
=> Add children props

.changeset/short-jobs-live.md
Changeset belonging to https://github.com/diegomura/react-pdf/pull/1723
=> chore: add missing changeset

.changeset/selfish-queens-tie.md, packages/render/src/primitives/renderImage.js
=> fix: image dimension warning for JSON sources

.changeset/hungry-llamas-stare.md, packages/layout/src/image/fetchImage.js, packages/pdfkit/src/image.js, packages/pdfkit/src/image/jpeg.js, packages/pdfkit/src/image/png.js, packages/pdfkit/src/mixins/images.js, packages/render/src/primitives/renderImage.js
Embed same image only once in final document, regardless how many times get's rendered
Also deleted some unused code and fixed linting issues
Fixes #1852
Before (127k):
[4d8f9d09-ccf4-4b2d-b304-1d93b2bf7a52.pdf](https://github.com/diegomura/react-pdf/files/8837061/4d8f9d09-ccf4-4b2d-b304-1d93b2bf7a52.pdf)
After (33k):
[7bb73b03-eaaf-47ca-a718-fced0120ad07.pdf](https://github.com/diegomura/react-pdf/files/8837060/7bb73b03-eaaf-47ca-a718-fced0120ad07.pdf)
=> feat: embed same image once in final document

.changeset/grumpy-birds-roll.md, packages/layout/src/text/linesWidth.js
=> fix: line width computation

.changeset/tame-rings-happen.md, packages/fontkit/src/glyph/CFFGlyph.js
=> fix: fontkit switch scoped vars

.changeset/tiny-rabbits-grab.md, packages/render/src/primitives/renderImage.js
=> fix: image opacity 0 rendering

.changeset/little-emus-cry.md, packages/pdfkit/src/mixins/annotations.js, packages/render/src/primitives/renderNote.js
Change background color and border with of notes
=> feat: add background color and border with Note support

.changeset/fluffy-tables-talk.md, packages/pdfkit/src/mixins/vector.js, packages/render/src/operations/transform.js, packages/stylesheet/src/transform/transform.js, packages/stylesheet/tests/transform.test.js
=> feat: add skew transformation support

.changeset/hot-pets-repeat.md, packages/layout/src/steps/resolveStyles.js, packages/layout/tests/steps/__snapshots__/resolveStyles.test.js.snap, packages/layout/tests/steps/resolveStyles.test.js
=> fix: media queries computing

.changeset/silent-moles-trade.md, packages/font/src/font.js
Related to #1891
Fixes need to polyfill font package, making bundle smaller for browser
=> feat: remove Buffer dependency from font package

.changeset/shiny-kiwis-lay.md, packages/renderer/index.d.ts
Re: https://github.com/diegomura/react-pdf/pull/1902#issuecomment-1176547351 — should've been `Function` type
=> fix: bad type on onClick

.github/CONTRIBUTING.md, .travis.yml, babel.config.js, package.json, yarn.lock
Update node 12 references + change babel config to node 14
=> chore: bump to node 14

.changeset/lemon-cameras-visit.md, packages/font/package.json, packages/font/src/font.js, yarn.lock
Fixes #2016
Fixes #1991, or at least the last thing stopping people from solving that issue for themselves by upgrading to Webpack 5
I tested this only in a browser build, using the following base64-encoded font:
```
Font.register({ family: 'Dangrek', src: 'data:font/truetype;charset=utf-8;base64,AAEAAAARAQAABAAQR0RFRgGQAVoAAAEkAAAAHEdQT1OxqajlAAAOBAAABDRHU1VChOgUYgAAG0gAAAnWT1MvMpL1jNAAAAIUAAAAYGNtYXCZ658iAAADKAAAATxjdnQgB0QaiwAAAbwAAABWZnBnbWIu/XwAACUgAAAODGdhc3AAAAAQAAABHAAAAAhnbHlml8xuSwAAMywAAL66aGVhZB5skoMAAAGEAAAANmhoZWEQwgsGAAABYAAAACRobXR44uNgUgAACiQAAAPebG9jYQMK0qoAAARkAAACJm1heHACnw86AAABQAAAACBuYW1lV+1y4AAABowAAAOWcG9zdEuRLyEAABI4AAAJDXByZXBpRAGiAAACdAAAALIAAQAB//8ADwABAAAADAAAAAAAAAACAAIAeAB5AAMA3AEGAAMAAQAAARIAggAQADEAAgACAEAAeACNAAAArA4MAAEAAQABAAAJxPtQAAAQaPcp/nAP0gABAAAAAA …
```
=> fix: Remove non-isomorphic and outdated dependency base64-to-uint8array

.changeset/tough-squids-cough.md, packages/pdfkit/rollup.config.js, packages/pdfkit/src/mixins/attachments.js
=> fix attachments mixin

.changeset/rich-hounds-own.md, packages/yoga/babel.config.js, packages/yoga/package.json, packages/yoga/rollup.config.js
=> Transpile modern js

.changeset/famous-chicken-perform.md, packages/renderer/rollup.config.js
=> Fix commonjs and esm entries

.changeset/dull-moons-lie.md, packages/renderer/index.d.ts
I failed to export it right in previous PR 😢
=> Export `renderToBuffer` type

.changeset/stupid-cheetahs-share.md, packages/renderer/tests/resume.test.js, packages/stylesheet/src/expand/flex.js
- because it breaks all flex layouts
=> Revert flex shorthand defaults

.changeset/config.json
always update internal packages to avoid problems like:
- https://github.com/diegomura/react-pdf/issues/2184#issuecomment-1423290750
=> chore: use experimental flag to always update internal packages

.changeset/tidy-countries-count.md, packages/renderer/src/index.js
=> reveal layout in onRender callback

.changeset/warm-impalas-behave.md, .eslintrc.js, babel.config.js, packages/renderer/README.md, packages/renderer/rollup.config.js, packages/renderer/src/dom/PDFDownloadLink.js, packages/renderer/src/dom/PDFViewer.js, packages/renderer/tests/debug.test.js, packages/renderer/tests/flex.test.js, packages/renderer/tests/gap.test.js, packages/renderer/tests/link.test.js, packages/renderer/tests/node.test.js, packages/renderer/tests/orphanTexts.test.js, packages/renderer/tests/pageWrap.test.js, packages/renderer/tests/resume.test.js, packages/renderer/tests/svg.test.js, packages/renderer/tests/svgs.js, packages/renderer/tests/text.test.js, packages/renderer/tests/transform.test.js
- configure automatic runtime for jsx
=> jsx runtime

packages/renderer/index.d.ts, packages/renderer/src/index.js, packages/renderer/src/node/renderTo.js
Close all issues that is related to `renderToString`
fix #1649
fix #1767
fix #1955
fix #2136
=> deprecate `renderToString`

packages/renderer/package.json, yarn.lock
=> chore: bump size-limit

.changeset/moody-jars-relax.md, packages/pdfkit/src/font/embedded.js
Based on: https://github.com/diegomura/react-pdf/pull/2408
Sorry @chihyux, I messed up your PR when trying to rebase changes and test them 😞 Accelerating this to publish now. I'll still add you as author :)
=> fix: copy-paste for registered font

.changeset/fifty-bugs-change.md, .changeset/hungry-beans-run.md, packages/render/package.json, packages/render/src/utils/parseColor.js, packages/stylesheet/package.json, yarn.lock
Fixes: #1623
- Defaults to black if passed color is invalid
- Bumps color-string dep
=> fix: color parse error

.changeset/cold-tips-work.md, packages/layout/src/steps/resolveInheritance.js, packages/layout/tests/steps/resolveInhritance.test.js
Fixes: https://github.com/diegomura/react-pdf/issues/2316
=> feat: make nested text inherit background colors

.changeset/short-rockets-begin.md, packages/examples/src/resume/Experience.jsx
This custom Item component actually accepts children only.
=> fix: invalid prop (style) in Resume example

.changeset/thin-windows-smell.md, packages/pdfkit/src/abstract_reference.js, packages/pdfkit/src/data.js, packages/pdfkit/src/document.js, packages/pdfkit/src/gradient.js, packages/pdfkit/src/image.js, packages/pdfkit/src/image/png.js, packages/pdfkit/src/metadata.js, packages/pdfkit/src/mixins/annotations.js, packages/pdfkit/src/mixins/color.js, packages/pdfkit/src/mixins/markings.js, packages/pdfkit/src/mixins/metadata.js, packages/pdfkit/src/mixins/outline.js, packages/pdfkit/src/mixins/vector.js, packages/pdfkit/src/name_tree.js, packages/pdfkit/src/outline.js, packages/pdfkit/src/pattern.js, packages/pdfkit/src/structure_content.js, packages/pdfkit/src/structure_element.js, packages/pdfkit/src/tree.js, packages/renderer/.size-limit.cjs
Converge lots of pdfkit files. Plan is to eventually switch to official package and remove fork, but it has proven harder than I thought due to several differences we accumulated over time
=> refactor: converge pdfkit

.changeset/cool-roses-teach.md, packages/render/src/operations/addMetadata.js, packages/render/tests/operations/addMetadata.test.js, packages/types/node.d.ts
Fixes: https://github.com/diegomura/react-pdf/issues/2536
Fixes: https://github.com/diegomura/react-pdf/issues/1375
=> feat: pass creation and modification dates

.changeset/cuddly-poets-rest.md, packages/image/src/resolve.js, packages/image/tests/resolve.test.js, packages/layout/tests/image/resolveSource.test.js, packages/types/image.d.ts
=> feat: add support for resolving blob images

.husky/pre-commit, package.json, packages/renderer/package.json, yarn.lock
This update brings simplified config and increased compatibility with Windows.
=> chore: update husky to 9.0.0

package.json, packages/types/image.d.ts
Also sneaking in changes in .d.ts file, which previously was not auto-formatted on commit because of this very issue I'm fixing rn.
=> chore: use ESLint and Prettier before commit on JSX and TS files too

.changeset/seven-bottles-wave.md, packages/layout/src/steps/resolvePagination.js, packages/layout/src/steps/resolveStyles.js
=> fix: resolve styles on dynamic elements

.changeset/great-badgers-pull.md, packages/image/package.json, packages/pdfkit/package.json, yarn.lock
Closes: https://github.com/diegomura/react-pdf/issues/2656
Closes: https://github.com/diegomura/react-pdf/issues/2651
Closes: https://github.com/diegomura/react-pdf/issues/2622
Closes: https://github.com/diegomura/react-pdf/issues/2632
=> chore: bump jay-peg dep

babel.config.js, package.json, yarn.lock
- remove unnecessary babel plugin
- change browserlist config
=> feat: improve babel config

packages/layout/src/svg/layoutText.js
Regression from https://github.com/diegomura/react-pdf/pull/2731
Fixes tests in master
=> fix: svg text rendering

.changeset/lemon-berries-hide.md, packages/renderer/src/dom/PDFDownloadLink.js
=> fix: download IE checks

.changeset/perfect-rats-raise.md, packages/image/package.json, packages/pdfkit/package.json, yarn.lock
Thanks for releasing jay-peg 1.1.0!
=> chore: bump jay-peg to 1.1.0

.github/workflows/release.yml
Reverts diegomura/react-pdf#2921
@farseekers CI is failing. Need to investigate but don't have the time now
=> Revert "chore: update node versions"

.changeset/wise-rocks-divide.md, packages/render/src/operations/transform.js
=> fix: skew transformation

.changeset/beige-tools-appear.md, packages/render/src/primitives/renderSvg.js
Fixes: https://github.com/diegomura/react-pdf/issues/2899
=> fix: stroke dash array computation

.changeset/smart-ligers-build.md, packages/stylesheet/src/transform/transform.js
=> feat: accept commas between transformations

.changeset/unlucky-coats-crash.md, packages/renderer/src/renderer.js
=> fix: note rendering

packages/png-js/README.md, packages/render/README.md, packages/stylesheet/README.md
Updates the repository READMEs to use ESM-first.
This follows up #2409 where it was established the project wants to prioritize ESM.
=> chore: update READMEs to use ESM-first

.changeset/fair-cougars-reflect.md, packages/pdfkit/src/document.js, packages/pdfkit/src/font_factory.js, packages/pdfkit/src/mixins/attachments.js, packages/pdfkit/src/mixins/text.js, packages/pdfkit/src/object.js, packages/pdfkit/src/page.js, packages/pdfkit/src/utils/capitalize.js, packages/pdfkit/src/virtual-fs.js, packages/render/src/primitives/renderGlyphs.js, packages/renderer/src/index.js, packages/renderer/src/utils.js
Unify more pieces of code with pdfkit to (eventually) remove our fork
=> refactor: partially unify pdfkit 

.changeset/fluffy-hotels-jam.md, packages/font/src/index.ts, packages/types/font.d.ts
=> fix: renderer types
